### ISSUE TITLE
Number items are updated every keypress

### ISSUE THREAD

**Issue by dylwhich** [idiotic/idiotic-webui#22]
They should only update with onchange to avoid putting things into an invalid state while typing.

**Comment by alexander-bauer** [comment]
Interestingly, these are already updated with [`ngChange`](https://docs.angularjs.org/api/ng/directive/ngChange#!), and should obey validation rules already. For example, on the Hackafe maximum/minimum temperature settings, typing letters refuses to send API call, becasue the state becomes `undefined` when the input does not validate. Could you provide a case in which this fails?

**Comment by dylwhich** [comment]
Say you're setting a dimmer's brightness from 100% to 50%. You don't want to change it to 10%, then 1%, then 0%, then 5%, then 50%; it should go directly from 100% to 50% when the user finishes changing it.

ngChange seems to behave differently than the actual [html/js onchange](http://www.w3schools.com/jsref/event_onchange.asp) attribute, which only takes effect once a field changes and loses focus.  [This post](http://stackoverflow.com/questions/11868393/angularjs-inputtext-ngchange-fires-while-the-value-is-changing) seems to describe achieving this behavior in angular, using ngBlur.

**Comment by alexander-bauer** [comment]
From that post, it looks like the easy way to do this is with [`ngModelOptions`](https://docs.angularjs.org/api/ng/directive/ngModelOptions) by setting `updateOn: "default blur", debounce: {"default": 500, "blur": 0}` in the model options. I think this will cause it to update immediately on loss of focus, and update after half a second of inactivity otherwise.
